### ISSUE TITLE
'make init' returns an error on MacOS M1

### ISSUE THREAD

**Issue by Jan-Piotraschke** [KAIZN-io/Voy#1]
If `docker compose up -d voy` gets executed in `make init`, it results in following error message:
 
> WARN[0000] The "DB_SERVICE_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_BACKUP_DIR" variable is not set. Defaulting to a blank string.
WARN[0000] The "VOY_SERVICE_PORT" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

> * error decoding 'Volumes[1]': invalid spec: :/backups/:cached: empty section between colons

**Comment by Jan-Piotraschke** [comment]
The problem was in my docker setup. After a reinstall, it worked but resulted in another issue after executing `make init` -> 
`docker compose exec voy voy database init`:

> psycopg2.OperationalError: FATAL:  password authentication failed for user "voy"

The `.env` file is the same as `.example.env`.

**Comment by janlucaklees** [comment]
Seems like you are having an old database volume flying around.

Please completely reset the setup by running `make clean`. (Make sure to pull the newest changes.)

Then try again with `make init`.

**Comment by Jan-Piotraschke** [comment]
This resolved the problem with the database but Voy still doesn't run:
<img width="1048" alt="Bildschirmfoto 2022-08-12 um 09 46 21" src="https://user-images.githubusercontent.com/78916218/184309368-0e29313b-2eaa-43e5-94de-3c9eca87c255.png">

If I access `localhost:5002`, I see the following error message in the browser: 

> Cannot GET /

**Comment by janlucaklees** [comment]
Please make sure to follow the instructions in the readme. The correct address is: http://localhost:5000/

**Comment by Jan-Piotraschke** [comment]
I know, but nothing runs on 5000

**Comment by Jan-Piotraschke** [comment]
And the screenshot states that the project is running at 5002. so there is a miss-match

**Comment by janlucaklees** [comment]
> If I access localhost:5002

Because of this i was under the impression, that you were trying to access the wrong address. (To be precise: the wrong port).

Yes, it does say so on the console. But I'd prefer you to stick to the README. 

What do you see, when you try to access localhost:5000?

Technical explanation of what you see on the console:
In modern frontend development - where you don't want to reload the whole page after every change you make, especially when you are just tweaking the styling (CSS) - you want to have some kind of server running that serves your frontend assets (CSS and JS that is). It just makes things much faster and enjoyable in development.
This other server needs to be accessible though. So it requires a port number to run on your localhost. I just chose 5002 to keep things together number wise. 
So what then happens is, when I access localhost:5000 I connect to the server running Flask. This in turn then connects to the frontend server running under localhost:5002 to get the assets for the frontend.

**Comment by janlucaklees** [comment]
After our call. I think we can close this.
